name: resto_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  android_alarm_manager: ^2.0.0
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.5.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.0.0
  flutter_local_notifications: ^8.1.1+1
  flutter_rating_bar: ^4.0.0
  flutter_screenutil: ^5.0.0+2
  get: ^4.3.8
  get_storage: ^2.0.3
  google_fonts: ^2.0.0
  google_sign_in: ^5.1.0
  http: ^0.13.3
  intl: ^0.17.0
  lottie: ^1.1.0
  readmore: ^2.1.0
  responsive_navigation_bar: ^2.1.2
  shimmer: ^2.0.0

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_launcher_icons: ^0.9.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  mockito: ^5.0.15
  test: ^1.16.8

flutter:
  uses-material-design: true
  assets:
    - assets/animation/
    - assets/icon/
