name: calculator
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.1.0
  math_expressions: ^2.2.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_launcher_icons: "^0.9.1"
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
